# Generated by Django 4.2.11 on 2024-04-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_hidden',
            field=models.BooleanField(blank=True),
        ),
    ]
