# Generated by Django 4.2.11 on 2024-04-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_rename_doctor_patient_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(related_name='patients', through='hospitals.Reservation', to='hospitals.doctor'),
        ),
    ]
