import Nav from "../../components/nav"

export const metadata = {
  title: 'About us',
  description: 'Generated by Next.js',
}

export default function AboutUs() {
  return (
    <div>
      <h1>About us!</h1>
    </div>
  )
}