# Generated by Django 4.2.11 on 2024-04-08 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='doctor',
            new_name='doctors',
        ),
    ]
