# Generated by Django 4.2.11 on 2024-04-08 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_rename_doctor_reservation_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor',
            new_name='doctors',
        ),
    ]
