import Nav from "../../components/nav"
import Avatar from "../../components/avatar"

export const metadata = {
  title: 'Home',
  description: 'Generated by Next.js',
}

// function 이름은 별로 상관 없음
export default function Page() {
  return (
    <div>
    <Avatar />
    </div>
  )
}